# Generated by Django 5.2.7 on 2025-12-10 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='membership',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='api.usermembership'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='api.booking'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('booking__isnull', False), ('membership__isnull', True)), models.Q(('booking__isnull', True), ('membership__isnull', False)), _connector='OR'), name='payment_must_have_booking_or_membership'),
        ),
    ]
