# Generated by Django 5.2.7 on 2025-12-15 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_payment_membership_alter_payment_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermembership',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Власник корпоративного абонементу', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MembershipInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(help_text='Email запрошеного користувача', max_length=254)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('token', models.CharField(help_text='Унікальний токен для прийняття запрошення', max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(help_text='Термін дії запрошення')),
                ('invited_by', models.ForeignKey(help_text='Користувач, який надіслав запрошення', on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(help_text='Корпоративний абонемент, до якого запрошують', on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='api.usermembership')),
            ],
            options={
                'unique_together': {('membership', 'email')},
            },
        ),
    ]
