# Generated by Django 5.2.7 on 2025-12-16 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_usermembership_owner_membershipinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Заголовок акції', max_length=255)),
                ('description', models.TextField(help_text='Опис акції')),
                ('scope', models.CharField(choices=[('GENERAL', 'Загальна'), ('PERSONAL', 'Персональна')], default='GENERAL', help_text='Загальна або персональна акція', max_length=20)),
                ('discount_type', models.CharField(choices=[('BOOKING', 'На бронювання'), ('SUBSCRIPTION', 'На абонемент'), ('INFO', 'Інформаційна')], default='INFO', help_text='Тип знижки', max_length=20)),
                ('discount_value_type', models.CharField(choices=[('PERCENTAGE', 'Відсоток'), ('FIXED', 'Фіксована сума')], default='PERCENTAGE', help_text='Тип значення знижки', max_length=20)),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, help_text='Значення знижки (відсоток або фіксована сума)', max_digits=10, null=True)),
                ('start_date', models.DateTimeField(help_text='Дата початку акції')),
                ('end_date', models.DateTimeField(help_text='Дата закінчення акції')),
                ('is_active', models.BooleanField(default=True, help_text='Чи активна акція')),
                ('target_section', models.ForeignKey(blank=True, help_text='Цільова секція (якщо знижка тільки на конкретну секцію)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.section')),
                ('target_subscription', models.ForeignKey(blank=True, help_text='Цільовий абонемент (якщо знижка тільки на конкретний тип)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.subscription')),
                ('target_user', models.ForeignKey(blank=True, help_text='Цільовий користувач для персональної акції', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_promotions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
            },
        ),
    ]
