# Generated by Django 5.2.7 on 2025-12-16 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='target_age_category',
            field=models.CharField(blank=True, help_text='Вікова категорія (Adults, Kids, або порожньо для всіх)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='target_center',
            field=models.ForeignKey(blank=True, help_text='Цільовий центр (якщо знижка тільки на конкретний центр)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sportcenter'),
        ),
    ]
